### ISSUE TITLE
Add support for setting the neo4j config.

### ISSUE THREAD

**Issue by eastlondoner** [michael-simons/junit-jupiter-causal-cluster-testcontainer-extension#43]
I'm not sure what the best way to do this is.

We could add a `Supplier<Map<String, String>>` to the annotation:
`@NeedsCausalCluster(config=MyClass.getNeo4jConfig())`

We could add an annotation that can be added to either a method or a field on a class which contains the config

```
@NeedsCausalCluster
public class AkkaRestartTests
{
    private final Logger log = LoggerFactory.getLogger( this.getClass() );

    @CausalCluster
    private static Neo4jCluster cluster;

    @CausalClusterConfig
    private static Map<String, String> config = Map.of("causal_clustering.middleware.logging.level", "DEBUG");
```

But perhaps you Java Wizards have some better ideas @meistermeier @michael-simons ?

**Comment by eastlondoner** [comment]
This PR: goes a bit further than allowing the user to set config - instead allowing them to manipulate the Neo4jContainers:
 https://github.com/michael-simons/junit-jupiter-causal-cluster-testcontainer-extension/pull/44

That approach has value for things like adding plugins and it would work for setting neo4j configuration. But there is still value in a neo4j.conf -specific annotation as it's less dangerous for people who only want to tweak config.

**Comment by michael-simons** [comment]
I like it better than the map approach. The modifier can still just produce a map of configs.
